// Mocks generated by Mockito 5.4.4 from annotations
// in thrivve_assignment/test/features/withdraw/data/data_soruces/withdraw_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chopper/chopper.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:thrivve_assignment/features/withdraw/data/services/withdraw_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeType_0 extends _i1.SmartFake implements Type {
  _FakeType_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WithdrawService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWithdrawService extends _i1.Mock implements _i2.WithdrawService {
  MockWithdrawService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChopperClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.ChopperClient);

  @override
  set client(_i3.ChopperClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Type get definitionType => (super.noSuchMethod(
        Invocation.getter(#definitionType),
        returnValue: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
      ) as Type);

  @override
  _i5.Future<_i3.Response<dynamic>> listPayment() => (super.noSuchMethod(
        Invocation.method(
          #listPayment,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #listPayment,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> confirmWithDraw() => (super.noSuchMethod(
        Invocation.method(
          #confirmWithDraw,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #confirmWithDraw,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
}
